// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0uizg06cFnMjD0XqGCjZGiqxEDfZRm80',
    appId: '1:561341163027:web:afb996186fc6aea72681e6',
    messagingSenderId: '561341163027',
    projectId: 'book-bridge-app',
    authDomain: 'book-bridge-app.firebaseapp.com',
    storageBucket: 'book-bridge-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtilMS6eO9n1H7Wj5QFZdoTXS0qxzyXes',
    appId: '1:561341163027:android:f9f3b6ce6347362d2681e6',
    messagingSenderId: '561341163027',
    projectId: 'book-bridge-app',
    storageBucket: 'book-bridge-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_44fFUAOJLjgMfKsLZM3TYhHOW2sE0-k',
    appId: '1:561341163027:ios:c911288c9e436ef62681e6',
    messagingSenderId: '561341163027',
    projectId: 'book-bridge-app',
    storageBucket: 'book-bridge-app.appspot.com',
    iosBundleId: 'com.example.bookBridge',
  );
}
